// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['building', 'testing-without-a-mac'],
    },
    {
      type: 'category',
      label: 'Project',
      items: ['contributing', 'roadmap'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['architecture', 'url-scheme', 'privacy-policy', 'release-process'],
    },
    {
      type: 'category',
      label: 'Engineering Notes',
      link: {
        type: 'doc',
        id: 'research/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'research',
        },
      ],
    },
  ],
};

export default sidebars;
